### ISSUE TITLE
Rapport :  pbl agrégation des informations 

### ISSUE THREAD

**Issue by Elletseg** [Berreip/VSP_Issues_tracker#108]
![TICKET](https://github.com/Berreip/VSP_Issues_tracker/assets/138294691/b7966554-110a-42bf-9389-55225db53227)
![TICKET 2](https://github.com/Berreip/VSP_Issues_tracker/assets/138294691/1c0dc1d9-a839-466b-8675-a0badfbbd514)

**Comment by Berreip** [comment]
inverser getTreatmentByAnimalForVisit
