### ISSUE TITLE
Ou sont passées les photos ? 

### ISSUE THREAD

**Issue by Elletseg** [Berreip/VSP_Issues_tracker#133]
Comment je récupère mes photos méga chef hein ?! :P
!

- [x] #136

- [x]  PAS de sélection/désélection des chips: seulement ajout et suppression
- [x]  On rajoute un Check quand la photo est sélectionnée
- REMOVED  Il faut un bouton pour ouvrir le dossier de photo
- [x]  Pour sélectionner une photo, on fait un appui long dessus

 Quand on passe en mode sélection:

- [x] on fait apparaitre un indicateur avec le nombre de photo sélectionnée
- [x] il faut une petite croix pour désélectionner tout

Quand une ou plusieurs photo sont sélectionnées on doit proposer les options suivantes dans la barre de headers:

- [x]  supprimer les photos (avec confirmations)

- [x]  On peut cliquer sur la photo pour la passer en plein écran
- [x]  Et avoir les informations du pieds
- [x]  On peut demander à ouvrir la photo dans le viewer du téléphone
- [x] Les photos doivent être nommées avec le pattern suivant: [FR][idx6][WorkingNumber x4]_[AVG]_[yyyy_MM_dd]_[numéro de la phto avec examen des fichiers présents].jpeg

**Comment by Berreip** [comment]
![image](https://github.com/Berreip/VSP_Issues_tracker/assets/24607424/01abbad1-371c-4555-8467-b7070aef9401)

**Comment by Berreip** [comment]
![image](https://github.com/Berreip/VSP_Issues_tracker/assets/24607424/41350acf-0e6d-46ae-a392-88e62bb7cf20)
