### ISSUE TITLE
Mettre les infos remplies de la visite en cours dans le tableau d'historique 

### ISSUE THREAD

**Issue by Elletseg** [Berreip/VSP_Issues_tracker#134]
Réfléchir sur la possibilité de rajouter une ligne avec la date de la visite en cours et les infos remplies de la visite en cours

**Comment by Berreip** [comment]
Est-ce que l'on doit toujours afficher la colonne avec les '...' conditionellement à la présence d'images et ou de commentaires ? on pourrait afficher toujours cette dernière. 

Et est ce que l'on garde un boutton pour accéder aux photo en plus du commentaire? est ce que les gens verront les '...' si c'est la seule manière d'y accéder?
