### ISSUE TITLE
[DESIGN] améliorer le design des filtres pour les photos

### ISSUE THREAD

**Issue by Berreip** [Berreip/VSP_Issues_tracker#135]
Il faudrait trouver un moyen d'intégrer plus de filtres d'une façon plus esthétique. merci ma mouhmouh

![image](https://github.com/Berreip/VSP_Issues_tracker/assets/24607424/a4feb060-416a-4df8-aa87-37c47bc33d77)

**Comment by Elletseg** [comment]
![image](https://github.com/Berreip/VSP_Issues_tracker/assets/138294691/2c9fba99-7f4d-4d19-8d25-9a54a12f9420)

**Comment by Elletseg** [comment]
![image](https://github.com/Berreip/VSP_Issues_tracker/assets/138294691/215dfdc9-a08b-4f35-b296-4c8eabc3a384)
