### ISSUE TITLE
en cliquant sur le bouton information d'un animal, on doit pouvoir afficher un écran de détails de ce dernier

### ISSUE THREAD

**Issue by Berreip** [Berreip/VSP_Issues_tracker#139]
Cet écran doit posséder:

- [x] le tableau d'historique tel que défini dans l'écran de visite

**Comment by Elletseg** [comment]
![image](https://github.com/Berreip/VSP_Issues_tracker/assets/138294691/b72e446c-d1cb-4a40-91f5-e9550a7c3bb8)
