### ISSUE TITLE
Améliorer design infos des photos 

### ISSUE THREAD

**Issue by Elletseg** [Berreip/VSP_Issues_tracker#147]

**Comment by Berreip** [comment]
![image](https://github.com/Berreip/VSP_Issues_tracker/assets/24607424/9785ed35-508c-457e-90ea-50f6b5cbe249)

**Comment by Berreip** [comment]
![image](https://github.com/Berreip/VSP_Issues_tracker/assets/24607424/85a41025-b2a7-4071-a5b6-46d76cec6b3b)

**Comment by Berreip** [comment]
![image](https://github.com/Berreip/VSP_Issues_tracker/assets/24607424/203be9c8-631f-4161-9d47-1024e7cc9d3b)

**Comment by Elletseg** [comment]
![image](https://github.com/Berreip/VSP_Issues_tracker/assets/138294691/8b547ebb-fe1c-4901-988b-2e2c07c307c3)

**Comment by Elletseg** [comment]
![image](https://github.com/Berreip/VSP_Issues_tracker/assets/138294691/09d4bf7c-ed5d-4c7e-a67c-87d9f48f4b90)

**Comment by Elletseg** [comment]
![image](https://github.com/Berreip/VSP_Issues_tracker/assets/138294691/fcd26d98-0387-4d49-80e4-21b33a770204)

**Comment by Berreip** [comment]
@Elletseg : Tu souhaite remplacer la boite transparente en surbrillance par une partie dépliante transparent c'est bien ça?

**Comment by Berreip** [comment]
finalement, on a simplement réduit l'opacité afin de ne pas perdre en lisibilité en fonction du couple luminosité photo/thème
