### ISSUE TITLE
Refaire l'écran d'affichage des images de pieds et pouvoir changer le pied/l'animal quand on a pris une photo 

### ISSUE THREAD

**Issue by Berreip** [Berreip/VSP_Issues_tracker#165]
**Description**
Si on s'est trompé, il faut pouvoir re-assigner la photo

- [x] load lesions and treatment
- [x] edit button + update foot type box
- [x] delete button + confirmation box

**Comment by Elletseg** [comment]
![image](https://github.com/Berreip/VSP_Issues_tracker/assets/138294691/2a3c25c2-5d0d-468b-88e2-f823736a483d)

**Comment by Elletseg** [comment]
![image](https://github.com/Berreip/VSP_Issues_tracker/assets/138294691/8770bd04-847e-4100-8440-fed3e6931dbb)
![image](https://github.com/Berreip/VSP_Issues_tracker/assets/138294691/d45fa6ef-2758-469e-b447-29775f6155c2)
