### ISSUE TITLE
Changer le design du pdf

### ISSUE THREAD

**Issue by Elletseg** [Berreip/VSP_Issues_tracker#171]
- [ ] Ajouter le logo en haut à droite
- [ ] Barre affichage du titre du rapport avec Parage + Date + Nom Elevage 
- [ ] Tableau récapitulatif correspond au  tableau d'historique par vache  
[TEST RAPPORT 2.docx](https://github.com/Berreip/VSP_Issues_tracker/files/12775522/TEST.RAPPORT.2.docx)

**Comment by Berreip** [comment]
premiers test pas concluant: trop petit, trop d'infos. A retravailler
