### ISSUE TITLE
Rajouter caractère infectieux d'un grade de lésion 

### ISSUE THREAD

**Issue by Elletseg** [Berreip/VSP_Issues_tracker#187]
**Description**

[Tableau des lésions et grade associé.xlsx](https://github.com/Berreip/VSP_Issues_tracker/files/13229452/Tableau.des.lesions.et.grade.associe.xlsx)

**Comment by Berreip** [comment]
Comment doit on l'indiquer? dans quel écran?

**Comment by Berreip** [comment]
pour le moment juste Méthode et Tests unitaires
