### ISSUE TITLE
trouver un moyen d'indiquer plus clairement comment créer un animal 

### ISSUE THREAD

**Issue by Berreip** [Berreip/VSP_Issues_tracker#190]
**Description**

**Comment by Berreip** [comment]
<string name="AnimalCreationFailDetails">Le texte fourni n\'a pas pu être analysé pour créer un animal. Il faut fournir au minimum les 4 chiffres du numéro de travail pour pouvoir créer un animal.</string>
    <string name="AnimalCreationFailDetailsPart2">Le format idéal attendu est de type: </string>
    <string name="AnimalCreationFailFormatDetails">FR 123456 7890 NOM_ANIMAL</string>
    <string name="AnimalCreationFailDetailsPart3">Si aucun code de pays n\'est fourni, FR est utilisé.</string>

**Comment by Elletseg** [comment]
![image](https://github.com/Berreip/VSP_Issues_tracker/assets/138294691/171ef4b1-c77a-41d4-aac3-535df9e4ec67)
![image](https://github.com/Berreip/VSP_Issues_tracker/assets/138294691/5f8b63b3-4f30-4f03-ab14-d3384e7cfbc2)
