### ISSUE TITLE
Corriger la couleur et passe sur le texte...

### ISSUE THREAD

**Issue by Elletseg** [Berreip/VSP_Issues_tracker#198]
**Description**
Regarder dans paramètres
Couleur texte sous les icones différents

**Comment by Berreip** [comment]
@Elletseg pour les couleurs des tabs, il y a un mélange entrer la volonté de rendre visible un état (sélectionné) et de signifier la présence d'un élément (il y a des lésions). En conséquence, j'ai choisi de ne PAS mettre en jaune pour indiquer la sélection (il y a déjà un indicateur de position) MAIS de m'en servir pour illustrer la présence de lésions ou de traitements
