### ISSUE TITLE
Travailler la partie tablette et téléphone de la vue Création de visites

### ISSUE THREAD

**Issue by Berreip** [Berreip/VSP_Issues_tracker#27]

**Comment by Elletseg** [comment]
![visuel ordi création visite](https://github.com/Berreip/VSP_Issues_tracker/assets/138294691/3adfeeaf-4723-4a74-9288-7e3135807bdb)

**Comment by Elletseg** [comment]
![visuel tablette création visite](https://github.com/Berreip/VSP_Issues_tracker/assets/138294691/c8675820-3ea1-4bb8-8076-dd6f85ec99bd)
