### ISSUE TITLE
faire l'icône de l'application en svg

### ISSUE THREAD

**Issue by Berreip** [Berreip/VSP_Issues_tracker#61]
Il faut séparer le cercle de fond ET le reste de l'icone

exemple:
![vsp_icon](https://github.com/Berreip/VSP_Issues_tracker/assets/24607424/50053229-69d1-4f24-8f86-e163b4d1da1f)

**Comment by Berreip** [comment]
@Elletseg bon courage

**Comment by Elletseg** [comment]
![icone appli  2svg](https://github.com/Berreip/VSP_Issues_tracker/assets/138294691/78b9ffe8-4999-43dd-bf7f-8477bcc3b3c7)

**Comment by Elletseg** [comment]
<svg xmlns="http://www.w3.org/2000/svg" viewBox="-1.01219 5.98781 82.02 82.02">
  <path d="M 41 6 A 1 1 0 0 0 39 88 A 1 1 0 0 0 41 6 Z M 31.929 76.983 C 31.929 64.889 35.984 48.099 15.647 34.923 C 13 32 14.047 30.924 17.308 33.016 C 29.368 42.336 37.763 48.597 34.763 77.167 C 34.738 79.916 31.961 80.037 31.953 77.094 Z M 43 78 C 52 61 85 51 69 33 C 56 18 57 21 62 32 C 68 45 44 50 42 63 C 42 68 42 71 41 77 C 41 80 42 80 43 78 Z M 61.226 26.329 C 88.758 51.229 54.752 53.862 43.44 74.92 C 43 75 43 75 44 68 C 47 54 75.896 50.088 61.497 27.764 Z M 13 31 C 7.92 31.445 7.358 30.672 5.392 27.02 C 9.915 26.995 11 27 13 31 Z M 21.347 34.457 C 17.7407 30.8515 17.9716 29.9241 19.5055 26.0706 C 22.432 29.5194 23.1256 30.3538 21.373 34.375 Z M 17 38 C 13.3945 41.6063 12.4671 41.3754 8.6136 39.8415 C 12.0624 36.915 12.8968 36.2214 17 38 Z M 13 35 C 8.8231 37.9254 7.9499 37.5369 4.4212 35.3572 C 8.3258 33.0741 9.268 32.5358 13 35 Z M 22 41 C 18.3945 44.6063 17.4671 44.3754 13.6136 42.8415 C 17.0624 39.915 17.8968 39.2214 22 41 Z M 17 31 C 12.8225 28.0755 12.8888 27.1221 13.7303 23.0608 C 17.2111 25.949 18.0391 26.6502 17 31 Z m 9 8 c -3.2783 -3.9061 -2.9674 -4.8098 -1.1035 -8.515 c 2.6147 3.6908 3.233 4.5823 1.1035 8.515 z" fill="#000000"/>
</svg>

**Comment by Elletseg** [comment]
<path d="M 41 6 A 1 1 0 0 0 39 88 A 1 1 0 0 0 41 6 Z M 31.929 76.983 C 31.929 64.889 35.984 48.099 15.647 34.923 C 13 32 14.047 30.924 17.308 33.016 C 29.368 42.336 37.763 48.597 34.763 77.167 C 34.738 79.916 31.961 80.037 31.953 77.094 Z M 43 78 C 52 61 85 51 69 33 C 56 18 57 21 62 32 C 68 45 44 50 42 63 C 42 68 42 71 41 77 C 41 80 42 80 43 78 Z M 61.226 26.329 C 88.758 51.229 54.752 53.862 43.44 74.92 C 43 75 43 75 44 68 C 47 54 75.896 50.088 61.497 27.764 Z M 13 31 C 7.92 31.445 7.358 30.672 5.392 27.02 C 9.915 26.995 11 27 13 31 Z M 21.347 34.457 C 17.7407 30.8515 17.9716 29.9241 19.5055 26.0706 C 22.432 29.5194 23.1256 30.3538 21.373 34.375 Z M 17 38 C 13.3945 41.6063 12.4671 41.3754 8.6136 39.8415 C 12.0624 36.915 12.8968 36.2214 17 38 Z M 13 35 C 8.8231 37.9254 7.9499 37.5369 4.4212 35.3572 C 8.3258 33.0741 9.268 32.5358 13 35 Z M 22 41 C 18.3945 44.6063 17.4671 44.3754 13.6136 42.8415 C 17.0624 39.915 17.8968 39.2214 22 41 Z M 17 31 C 12.8225 28.0755 12.8888 27.1221 13.7303 23.0608 C 17.2111 25.949 18.0391 26.6502 17 31 Z m 9 8 c -3.2783 -3.9061 -2.9674 -4.8098 -1.1035 -8.515 c 2.6147 3.6908 3.233 4.5823 1.1035 8.515 z">
