### ISSUE TITLE
réfléchir à l'historique de la visite 

### ISSUE THREAD

**Issue by Berreip** [Berreip/VSP_Issues_tracker#70]
@Elletseg 
Que doit-on afficher en cliquant sur l'historique de la visite ?:

l'état de la visite en cours (la liste des vaches vues et les pathologies)
Le document pdf pour la visite "en l'état"
...
VA VOIR LES COMMENTAIRES MOUHMOUH !!!! Parce que j'ai la flemme de tout réécrire ! mouah !

**Comment by Elletseg** [comment]
![image](https://github.com/Berreip/VSP_Issues_tracker/assets/138294691/deb298f9-f5e5-468e-b6f7-8158fae15c00)

**Comment by Elletseg** [comment]
Quand clic sur ... pop up vers commentaires de la visite et photo jointes

**Comment by Elletseg** [comment]
Si pas de commentaires ni  de photos ,  pas de  ... dans la dernière colonne du tableau historique de la vache

**Comment by Elletseg** [comment]
Si on clic dans ... pop up affichant la date sélectionnée, le commentaire si existant et les photos de pieds faites scrollable

**Comment by Elletseg** [comment]
Si absence de lésion sur le pieds, mettre un rond barré dans le tableau
Si pieds non regardé pendant la visite, laissé case vide

**Comment by Berreip** [comment]
![image](https://github.com/Berreip/VSP_Issues_tracker/assets/24607424/6e451c79-f898-4dd9-a68c-9b207e3308ea)

**Comment by Elletseg** [comment]
Quand clic sur la loupe => recharge la visite de la vache selectionnée

**Comment by Elletseg** [comment]
Faudrait rajouter un compteur du nombre de vache faites sur la pop up historique de la visite

**Comment by Berreip** [comment]
![image](https://github.com/Berreip/VSP_Issues_tracker/assets/24607424/89706c27-674f-4a1d-af7b-2519ff4f2585)

**Comment by Elletseg** [comment]
![image](https://github.com/Berreip/VSP_Issues_tracker/assets/138294691/6d698e82-acc0-4bd3-a4e3-3575fbbfee59)

**Comment by Elletseg** [comment]
Mettre en valeur en jaune l'icone historique quand on est sur la page historique
