### ISSUE TITLE
Bug sur lorsqu'un traitement est sélectionné # 1

### ISSUE THREAD

**Issue by Elletseg** [Berreip/VSP_Issues_tracker#73]
- Ouverture visite
- Création vache 6575 
- Clic sur le pied en zone 4 
- Affichage du panneau des lésions : clic sur ulcère de la sole
- Affichage du panneau des lésions : Pas de traitement sélectionné 
- Clic sur le pied en zone 13 
- Affichage du panneau des lésions : Dermatite digitale
- Affichage des traitements : clic sur Pansement 
- Retour sur le panneau affichage du pied

Observé : 
- Affichage du pied : la zone 4 est désélectionnée 

Attendu : 
- Zone 4 et Zone 13 toujours affichées

**Comment by Berreip** [comment]
le simple fait d'ajouter un traitement, même sans changer de zones suffit à déclencher le bug: aie aie aie ^^

**Comment by Berreip** [comment]
je m'étais troué entre le traitement et le 'pas de lésions' et je virais explicitement les lésions lors de l'ajout d'un traitement... fatigue probablement :-p
