### ISSUE TITLE
Mode téléphone: Quand seulement un traitement est sélectionné, aucun indicateur de couleur n'est affiché sur le pieds

### ISSUE THREAD

**Issue by Berreip** [Berreip/VSP_Issues_tracker#80]
Step to Reproduce:

1) Dans l'écran des visites, sélectionner le pied AVD
2) Lui appliquer un traitement

Expected:
- [ ] on devrait avoir un indicateur jaune pour le bouton AvD

Observed:
on n'a aucune retour visuel signalant qu'un traitement est associé

![image](https://github.com/Berreip/VSP_Issues_tracker/assets/24607424/bd3650b7-3f61-4014-8f44-d5a703b7edb3)

**Comment by Berreip** [comment]
@Elletseg  Voir ce qu'on doit avoir comme indicateur

**Comment by Elletseg** [comment]
JAUNE :-P 
MOUAH
