### ISSUE TITLE
Il n'y a aucun moyen de visualiser les phote de la visite en cours

### ISSUE THREAD

**Issue by Berreip** [Berreip/VSP_Issues_tracker#89]
@Elletseg Que décide t'on?
-> un bouton en plus? 
-> on fait apparaitre la vache de la visite actuelle dans le tableau? avec un indicateur? lequel?

**Comment by Elletseg** [comment]
Pour chaque animal vu aujourd'hui on doit pouvoir visualiser les infos de la viste en cours dans le tableau historique de la vache 
On fait une ligne dans le tableau avec la date du jour et les infos des pieds et les photos dans les "... "
Mouah !!

**Comment by Elletseg** [comment]
Sinon date d'aujourd'hui écrit en jaune ? 
Ou un "auj."

**Comment by Berreip** [comment]
Après essai, c'est pas optimum car je ne rechargeais tout le tableau depuis la base de données qu'au changement d'animal. 
Si on affiche le détail de la visite actuelle, il faut le rafraichir à chaque action sauvegardé en base, ce qui est très très fréquent...

Je vais temporiser en mettant un bouton pour afficher les photos de la visite dans l'onglet général.
